//
// Copyright © 2022 Anonyome Labs, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

import Foundation

/// Representation of a Funding Source used in Platform SDK.
public struct FundingSource: Hashable {

    // MARK: - Supplementary

    /// State type associated with `FundingSource`.
    /// - active: funding source is active.
    /// - inactive: funding source is inactive.
    /// - unknown: type could not be discerned - associated value is unknown and suggests that the SDK version is out of sync with the service.
    public enum State: Hashable {
        case active
        case inactive
        case unknown(String)

        // MARK: - Lifecycle

        /// Initialize an instance of `FundingSource.State`.
        init(_ state: GraphQL.FundingSourceState) {
            switch state {
            case .active:
                self = .active
            case .inactive:
                self = .inactive
            case let .unknown(state):
                self = .unknown(state)
            }
        }
    }

    /// Network type associated with `FundingSource`.
    public enum Network: Hashable {
        case amex
        case diners
        case discover
        case jcb
        case mastercard
        case unionpay
        case visa
        case other
        case unknown(String)

        /// Initialize an instance of `FundingSource.Network`.
        init(_ network: GraphQL.CreditCardNetwork) {
            switch network {
            case .amex:
                self = .amex
            case .diners:
                self = .diners
            case .discover:
                self = .discover
            case .jcb:
                self = .jcb
            case .mastercard:
                self = .mastercard
            case .unionpay:
                self = .unionpay
            case .visa:
                self = .visa
            case .other:
                self = .other
            case let .unknown(type):
                self = .unknown(type)
            }
        }
    }

    // MARK: - Properties

    /// Identifier generated by the Virtual Cards Service.
    public var id: String

    /// Owner identifier of the funding source. Typically the user id.
    public var owner: String

    /// Version assigned by the service.
    public var version: Int

    /// Current state of the funding source.
    public var state: State

    /// Currency of the funding source.
    public var currency: String

    /// Last 4 digits of the card of the funding source.
    public var last4: String

    /// Payment Method network of the funding source.
    public var network: Network

    /// VirtualCards service timestamp to when the funding source record was created.
    public var createdAt: Date

    /// VirtualCards service timestamp to when the funding source record was last updated.
    public var updatedAt: Date

    // MARK: - Lifecycle

    /// Initialize an instance of `FundingSource`.
    public init(id: String, owner: String, version: Int, state: State, currency: String, last4: String, network: Network, createdAt: Date, updatedAt: Date) {
        self.id = id
        self.owner = owner
        self.version = version
        self.state = state
        self.currency = currency
        self.last4 = last4
        self.network = network
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }

}
