//
// Copyright © 2022 Anonyome Labs, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

import Foundation

public protocol VirtualCardAttributes {

    /// Identifier generated by the Virtual Cards Service.
    var id: String { get set }

    /// List of identifiers of user/accounts associted with this card.
    ///
    /// Typically, this will consist of at least the user id and sudo id of the account.
    var owners: [Owner] { get set }

    /// Owner Id of the card.
    var owner: String { get set }

    /// Virtual cards service supplied version.
    var version: Int { get set }

    /// Associative Id of the funding source used to provision the card.
    var fundingSourceId: String { get set }

    /// Current state of the cards status.
    var state: VirtualCardState { get set }

    /// Owner of the card.
    var cardHolder: String { get set }

    /// Last 4 digits on the card.
    var last4: String { get set }

    /// Currency ISO code associated with the Card.
    var currency: String { get set }

    /// Date of the cards active to period.
    var activeTo: Date { get set }

    /// Date that the card was cancelled at.
    var cancelledAt: Date? { get set }

    /// VirtualCards service timestamp to when the card entry was created.
    var createdAt: Date { get set }

    /// VirtualCards service timestamp to when the card entry was last updated.
    var updatedAt: Date { get set }

}
