//
// Copyright © 2022 Anonyome Labs, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

import Foundation

public protocol TransactionAttributes {

    /// Identifier generated by the Virtual Cards Service.
    var id: String { get set }

    /// Associated Card ID of the transaction.
    var cardId: String { get set }

    /// Associated Sequence ID of the transaction. Used to identify related transactions.
    var sequenceId: String { get set }

    /// Type of the transaction.
    var type: TransactionType { get set }

    var sortDate: Date { get set }

    /// Date stamp that the transaction was created on the Virtual Cards Service.
    var createdAt: Date { get set }

    /// Date stamp that the transaction was last updated on the Virtual Cards Service.
    var updatedAt: Date { get set }

}
