//
// Copyright © 2023 Anonyome Labs, Inc. All rights reserved.
//
// SPDX-License-Identifier: Apache-2.0
//

import Combine
import Foundation
import SudoUser
import SudoLogging
import SudoApiClient

/// Abstraction of the SDKs capabilities surrounding `VirtualCard` access/manipulation with virtual cards service.
class VirtualCardService {

    /// Default values used in `CardService`.
    enum Defaults {
        /// Limit used when listing cards. 100 was set as it is unlikely a user will go over this number.
        static let provisionalCardListLimit = 100
        /// Timeout for a provision card observer before it is removed.
        static let provisionTimeout: TimeInterval = 60.0
        /// The amount of time to wait between polling attempts.
        static let provisionPollInterval: TimeInterval = 1
    }

    // MARK: - Properties

    /// App Sync Client used to interact with the GraphQL endpoint of the virtual cards service.
    private unowned let graphQLClient: SudoApiClient

    /// Unsealer used to unseal card data that has been encrypted.
    private unowned let unsealer: Unsealer

    private unowned let platformKeyManager: PlatformKeyManager

    /// Logs errors and diagnostic information.
    private let logger: Logger

    // MARK: - Lifecycle

    /// Initialize an instance of `CardService`.
    init(
        graphQLClient: SudoApiClient,
        unsealer: Unsealer,
        platformKeyManager: PlatformKeyManager,
        logger: Logger = .virtualCardsSDKLogger
    ) {
        self.graphQLClient = graphQLClient
        self.unsealer = unsealer
        self.platformKeyManager = platformKeyManager
        self.logger = logger
    }

    // MARK: - CardService

    /// Create a card.
    ///
    /// Calls the mutation to create a card against the GraphQL endpoint of the virtual cards service.
    /// - Parameters:
    ///   - input: Input supplied by the user.
    ///   - publicKey: Registered public key used to encrypt the card information.
    ///   - owner: Owner identifier of user. This is the user's account identifier.
    ///   - clientRefId: Client reference identifier generated by the `DefaultSudoVirtualCardsClient`.
    /// - Returns:
    ///     - Success: The provisioned Virtual Card.
    ///     - Failure: Any `Error` that may have occurred during the provisioning of the card, either internally or from the service.
    func create(
        withInput input: ProvisionVirtualCardInput,
        publicKey: PublicKey,
        owner: String,
        clientRefId: String
    ) async throws -> VirtualCard {
        // Double optional on purpose to ensure that gets passed as undefined on nil
        let billingAddressInput: GraphQL.AddressInput??
        if let address = input.billingAddress {
            billingAddressInput = GraphQL.AddressInput(
                addressLine1: address.addressLine1,
                addressLine2: address.addressLine2,
                city: address.city,
                country: address.country,
                postalCode: address.postalCode,
                state: address.state
            )
        } else {
            billingAddressInput = Optional(nil)
        }
        // Double optional on purpose to ensure that gets passed as undefined on nil
        let metadataInput: GraphQL.SealedAttributeInput??
        if let metadata = try sealMetadata(input.metadata) {
            metadataInput = metadata
        } else {
            metadataInput = Optional(nil)
        }
        // Double optional on purpose to ensure that gets passed as undefined on nil
        let aliasInput: String??
        if let alias = input.alias {
            aliasInput = alias
        } else {
            aliasInput = Optional(nil)
        }
        let request = GraphQL.CardProvisionRequest(
            alias: aliasInput,
            billingAddress: billingAddressInput,
            cardHolder: input.cardHolder,
            clientRefId: clientRefId,
            currency: input.currency,
            fundingSourceId: input.fundingSourceId,
            keyRingId: publicKey.keyRingId,
            metadata: metadataInput,
            ownerProofs: [input.ownershipProof]
        )
        let mutation = GraphQL.ProvisionVirtualCardMutation(input: request)
        let data: GraphQL.ProvisionVirtualCardMutation.Data
        do {
            data = try await graphQLClient.perform(mutation: mutation)
        } catch {
            throw SudoVirtualCardsError.fromApiOperationError(error: error)
        }
        let provisionalCardState = data.cardProvision.getProvisioningState()

        if provisionalCardState == .provisioning {
            logger.debug("Provision card mutation succeeded, will begin polling for completed state.")
            let virtualCard = try await pollForVirtualCard(clientRefId: clientRefId)
            return virtualCard
        } else {
            logger.error("Invalid provisioning state after provision card mutation: \(provisionalCardState.rawValue)")
            throw SudoVirtualCardsError.provisionFailed
        }
    }

    func update(
        withInput input: UpdateVirtualCardInput,
        keyId: String
    ) async throws -> SingleAPIResult<VirtualCard, PartialVirtualCard> {
        var request = GraphQL.CardUpdateRequest(cardHolder: input.cardHolder, id: input.id, keyId: keyId)
        switch input.alias {
        case .null:
            // Must be single optional to ensure that is passed as null
            let alias: String? = nil
            request.alias = alias
        case .undefined:
            let alias: String?? = nil
            request.alias = alias
        case .defined(let alias):
            request.alias = alias
        }

        switch input.billingAddress {
        case .null:
            // Must be single optional to ensure that is passed as null
            let billingAddress: GraphQL.AddressInput? = nil
            request.billingAddress = billingAddress
        case .undefined:
            let billingAddress: GraphQL.AddressInput?? = nil
            request.billingAddress = billingAddress
        case .defined(let address):
            request.billingAddress = GraphQL.AddressInput(
                addressLine1: address.addressLine1,
                addressLine2: address.addressLine2,
                city: address.city,
                country: address.country,
                postalCode: address.postalCode,
                state: address.state
            )
        }
        switch input.metadata {
        case .null:
            // Must be single optional to ensure that is passed as null
            let metadata: GraphQL.SealedAttributeInput? = nil
            request.metadata = metadata
        case .undefined:
            let metadata: GraphQL.SealedAttributeInput?? = nil
            request.metadata = metadata
        case .defined(let value):
            request.metadata = try sealMetadata(value)
        }

        if let expectedCardVersion = input.expectedCardVersion {
            request.expectedVersion = expectedCardVersion
        }

        let mutation = GraphQL.UpdateVirtualCardMutation(input: request)
        let data: GraphQL.UpdateVirtualCardMutation.Data
        do {
            data = try await graphQLClient.perform(mutation: mutation)
        } catch {
            throw SudoVirtualCardsError.fromApiOperationError(error: error)
        }
        do {
            let result = try unsealer.unseal(data.updateCard.fragments.sealedCardWithLastTransaction)
            return .success(result)
        } catch {
            let card = data.updateCard.fragments.sealedCardWithLastTransaction
            return .partial(PartialResult(card: card, error: error))
        }
    }

    // MARK: - Helpers

    func sealMetadata(_ metadata: JSONValue?) throws -> GraphQL.SealedAttributeInput? {
        guard let metadata = metadata else {
            return nil
        }
        var secretKeyId = try platformKeyManager.getCurrentSymmetricKeyId()
        if secretKeyId == nil {
            secretKeyId = try platformKeyManager.generateNewCurrentSymmetricKey()
        }
        guard let secretKeyId = secretKeyId else {
            throw SudoVirtualCardsError.fatalError(description: "Unexpected nil key after generating new key")
        }
        let serializedMetadata = try JSONSerialization.data(withJSONObject: metadata.toSwiftObject(), options: [.fragmentsAllowed, .sortedKeys])
        let encryptedMetadata = try platformKeyManager.encrypt(withSymmetricKeyId: secretKeyId, data: serializedMetadata)
        return GraphQL.SealedAttributeInput(
            algorithm: SymmetricKeyEncryptionAlgorithm.aesCBCPKCS7Padding.rawValue,
            base64EncodedSealedData: encryptedMetadata.base64EncodedString(),
            keyId: secretKeyId,
            plainTextType: "json-string"
        )
    }

    func pollForVirtualCard(clientRefId: String) async throws -> VirtualCard {
        let deadline = Date().addingTimeInterval(Defaults.provisionTimeout)
        while Date() < deadline {
            logger.debug("Polling for provisioned Virtual Card...")

            if let virtualCard = try await getVirtualCard(clientRefId: clientRefId) {
                logger.debug("Provisioned Virtual Card found.")
                return virtualCard
            } else {
                logger.debug("Virtual Card not provisioned yet, waiting for \(Defaults.provisionPollInterval) second/s.")
                try await Task.sleep(seconds: Defaults.provisionPollInterval)
            }
        }
        logger.error("Timed out after \(Defaults.provisionTimeout) seconds polling for provisioned Virtual Card.")
        throw SudoVirtualCardsError.cardNotFound
    }

    func getVirtualCard(clientRefId: String) async throws -> VirtualCard? {
        let filter = GraphQL.ProvisionalCardFilterInput(clientRefId: .init(eq: clientRefId))
        let query = GraphQL.ListProvisionalCardsQuery(filter: filter, limit: Defaults.provisionalCardListLimit)
        let data: GraphQL.ListProvisionalCardsQuery.Data
        do {
            data = try await graphQLClient.fetch(query: query)
        } catch {
            throw SudoVirtualCardsError.fromApiOperationError(error: error)
        }
        guard let provisionalCard = data.listProvisionalCards.items.first(where: { $0.clientRefId == clientRefId }) else {
            return nil
        }
        switch provisionalCard.getProvisioningState() {
        case .completed:
            var cardToUnseal: GraphQL.SealedCard?
            let sealedCards = provisionalCard.card?.map { $0.fragments.sealedCard } ?? []
            for sealedCard in sealedCards {
                if try await platformKeyManager.getKeyPairWithId(sealedCard.keyId) != nil {
                    cardToUnseal = sealedCard
                    break
                }
            }
            guard let cardToUnseal else {
                logger.error("Provisional card in completed provisioning state but sealed Virtual Card not found in fragments.")
                throw SudoVirtualCardsError.cardNotFound
            }
            do {
                return try unsealer.unseal(cardToUnseal)
            } catch {
                let errorMessage = "Failed to unseal Virtual Card: \(error.localizedDescription)"
                logger.error(errorMessage)
                throw SudoVirtualCardsError.internalError(errorMessage)
            }
        case .failed:
            logger.error("Provisional card in transitioned to failed state.")
            throw SudoVirtualCardsError.provisionFailed

        case .provisioning, .unknown:
            return nil
        }
    }
}
